/**
 * This is the Signum Assembler Language definition based on the work from
 * deleterium: https://github.com/deleterium/SmartC/blob/main/src/assembler/assembler.ts
 * ciyam: https://github.com/ciyam/AT/blob/master/docs/at.html
 *
 */

export const AsmKeywords = {
  // ASM opcodes grouped by categories
  programFlow: [
    "JMP",
    "JSR",
    "BZR",
    "BNZ",
    "BGZ",
    "BLZ",
    "BGE",
    "BLE",
    "BZS",
    "BNS",
    "BEQ",
    "STP",
    "SLP",
    "ERR",
    "FIZ",
    "FIN",
    "STZ",
  ],

  stackOperations: [
    "SET",
    "PCS",
    "PSH",
    "POP",
    "DUP",
    "SWP",
    "ROL",
    "ROR",
    "DLV",
    "PSC",
    "RET",
    "CLR"
  ],

  arithmeticOperations: [
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "MOD",
    "POW",
    "NOT",
    "AND",
    "OR",
    "XOR",
    "SHL",
    "SHR",
    "INC",
    "DEC",
    "MIN",
    "MAX",
    "MDV",
    "NEG",
  ],

  apiCalls: ["FUN", "API"],

  memoryOperations: [
    "LDA",
    "STA",
    "DAT",
    "LDI",
    "STI",
    "CLD",
    "CST",
    "ZLD",
    "DEL",
    "ILD",
    "IST",
  ],

  dataTypes: ["DAT", "IDX", "FUN", "API", "PCS", "VAR"],

  // directives: [
  //   "__program_begin",
  //   "__program_end",
  //   "__functions_begin",
  //   "__functions_end",
  //   "__data_begin",
  //   "__data_end",
  //   "_ASM_MAPS_BEGIN",
  //   "_ASM_MAPS_END",
  // ],

  operators: [
    "=",
    ":",
    ",",
    "+",
    "-",
    "*",
    "/",
    "%",
    "&",
    "|",
    "^",
    "!",
    "~",
    "<",
    ">",
    "$",
  ],

  // API function names for syntax highlighting
  apiFunctions: [
    "get_A1", "get_A2", "get_A3", "get_A4",
    "get_B1", "get_B2", "get_B3", "get_B4",
    "set_A1", "set_A2", "set_A3", "set_A4",
    "set_A1_A2", "set_A3_A4",
    "set_B1", "set_B2", "set_B3", "set_B4",
    "set_B1_B2", "set_B3_B4",
    "clear_A", "clear_B", "clear_A_B",
    "copy_A_From_B", "copy_B_From_A",
    "check_A_Is_Zero", "check_B_Is_Zero", "check_A_equals_B",
    "swap_A_and_B",
    "OR_A_with_B", "OR_B_with_A",
    "AND_A_with_B", "AND_B_with_A",
    "XOR_A_with_B", "XOR_B_with_A",
    "add_A_to_B", "add_B_to_A",
    "sub_A_from_B", "sub_B_from_A",
    "mul_A_by_B", "mul_B_by_A",
    "div_A_by_B", "div_B_by_A",
    "MD5_A_to_B", "check_MD5_A_with_B",
    "HASH160_A_to_B", "check_HASH160_A_with_B",
    "SHA256_A_to_B", "check_SHA256_A_with_B",
    "Check_Sig_B_With_A",
    "get_Block_Timestamp", "get_Creation_Timestamp", "get_Last_Block_Timestamp",
    "put_Last_Block_Hash_In_A",
    "A_to_Tx_after_Timestamp",
    "get_Type_for_Tx_in_A", "get_Amount_for_Tx_in_A", "get_Timestamp_for_Tx_in_A", "get_Ticket_Id_for_Tx_in_A",
    "message_from_Tx_in_A_to_B",
    "B_to_Address_of_Tx_in_A", "B_to_Address_of_Creator",
    "Get_Code_Hash_Id",
    "B_To_Assets_Of_Tx_In_A",
    "get_Current_Balance", "get_Previous_Balance",
    "send_to_Address_in_B", "send_All_to_Address_in_B", "send_Old_to_Address_in_B", "send_A_to_Address_in_B",
    "add_Minutes_to_Timestamp",
    "Get_Map_Value_Keys_In_A", "Set_Map_Value_Keys_In_A",
    "Issue_Asset", "Mint_Asset",
    "Distribute_To_Asset_Holders",
    "Get_Asset_Holders_Count",
    "Get_Activation_Fee",
    "Put_Last_Block_GSig_In_A",
    "Get_Asset_Circulating",
    "Get_Account_Balance"
  ],

  // we include these common regular expressions
  symbols: /[=><!~?:&|+\-*\/^%]+/,
};
