// GENERATED by scripts/i18n-types.ts from locales/en — do not edit.
// Run `bun run i18n:types` after changing an English JSON file.

export type MessageParams = {
};

export type MessageKey = keyof MessageParams;
