#!/usr/bin/env bun
/**
 * Writes src/i18n/keys.generated.ts from the English messages. JSON imports
 * type every leaf as `string`, so the placeholders a key needs are only
 * knowable by reading the text — which is what this does.
 */
import path from "path";
import { flattenMessages } from "../src/i18n/flatten";
import type { Messages } from "../src/i18n/runtime";

const PLACEHOLDER = /\{(\w+)\}/g;

function placeholders(text: string): string[] {
  return [...text.matchAll(PLACEHOLDER)].map((m) => m[1]);
}

export function generateKeyTypes(tree: Messages): string {
  const lines: string[] = [];
  for (const [key, leaf] of flattenMessages(tree)) {
    const isPlural = typeof leaf !== "string";
    const texts = isPlural ? Object.values(leaf) : [leaf];
    const names = [...new Set(texts.flatMap(placeholders))].filter(
      (n) => !(isPlural && n === "count"),
    );
    names.sort();
    const fields = [
      ...(isPlural ? ["count: number"] : []),
      ...names.map((n) => `${n}: string | number`),
    ];
    const type = fields.length ? `{ ${fields.join("; ")} }` : "undefined";
    lines.push(`  ${JSON.stringify(key)}: ${type};`);
  }
  return (
    "// GENERATED by scripts/i18n-types.ts from locales/en — do not edit.\n" +
    "// Run `bun run i18n:types` after changing an English JSON file.\n\n" +
    "export type MessageParams = {\n" +
    lines.join("\n") +
    (lines.length ? "\n" : "") +
    "};\n\n" +
    "export type MessageKey = keyof MessageParams;\n"
  );
}

if (import.meta.main) {
  const { default: en } = await import("../src/i18n/locales/en");
  const out = path.join(import.meta.dir, "../src/i18n/keys.generated.ts");
  await Bun.write(out, generateKeyTypes(en));
  console.log(`wrote ${path.relative(process.cwd(), out)}`);
}
